spring:
  application:
   name: payment-service
  config:
    import: optional:configserver:http://localhost:8888

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}

platform:
  commission-rate: ${PLATFORM_COMMISSION_RATE:0.10}
  payout-settlement-cron: ${PAYOUT_SETTLEMENT_CRON:0 0 3 * * *}

application:
  config:
    seller-url: ${SELLER_SERVICE_URL:http://localhost:8095/api/v1/sellers}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus