spring:
  profiles:
    active: git
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RajithaUBandara21/e-com-app-config.git
          username: RajithaUBandara21
          password: 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
          default-label: main
server:
  port: 8888
